// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "translation": {
    "about-packet-panic": {
      "paragraph1": "Packet Panic is een educatief spel dat is ontwikkeld door Studio Tast voor de SIDN-call 'Internet in beeld' om de onderliggende infrastructuur van het internet begrijpelijk uit te leggen.",
      "paragraph2": "Packet Panic focust op de gevaren van BGP-hijacking: het manipuleren en onderscheppen van internetverkeer door cybercriminelen. Het BGP is een essentieel, maar kwetsbaar onderdeel van het internet. Het internet is ontwikkeld door een groep onderzoekers die op basis van vertrouwen met elkaar samenwerkten. Het BGP gaat nog steeds uit van datzelfde onderlinge vertrouwen. Er zijn manieren om het BGP minder kwetsbaar te maken. Maar die zijn alleen effectief als die breed geimplementeerd worden. ",
      "paragraph3": "Het doel van Packet Panic is om meer mensen bewust te maken van de kwetsbaarheden van het Border Gateway Protocol (BGP). Via het spel krijgen spelers een inzicht in hoe BGP-hijacking werkt, wat de gevaren zijn en welke oplossingen er beschikbaar zijn.",
      "title": "Over Packet Panic"
    },
    "end-screen": {
      "go-to": "Ga naar",
      "news-review-title": "Terugblik krantenknipsels",
      "paragraph1": "Hopelijk heb je het gevoel gehad steeds achter de feiten aan te lopen. Wat als je meldingen krijgt dat een website niet beschikbaar is? Hoe weet je zeker dat een door het BGP aangekondigde route betrouwbaar is?",
      "paragraph2": "Packet Panic is bewust een frustrerend spel. Omdat BGP-hijacks een frustrerende realiteit zijn. RPKI is een goede oplossing, maar werkt pas echt goed bij 100% adoptie. Daar zijn we nog niet. De teller blijft vooralsnog steken op 50%",
      "paragraph3": "Nu weet jij dat ook. Dus help mee om RPKI adoptie naar 100% te krijgen.",
      "paragraph4": "Bedankt voor het spelen van Packet Panic.",
      "play-again": "Opnieuw spelen",
      "title": "Gefeliciteerd, je hebt Packet Panic voltooid!",
      "what-to-do": {
        "check-rpki": {
          "description": "en controleer hoe het zit met RPKI adoptie van je werkgever, je gemeente of je voetbalclub.",
          "title": "Check RPKI-adoptie"
        },
        "deepen-knowledge": {
          "description": "Bekijk de zusterprojecten van Packet Panic, die inzicht bieden in andere onderdelen van de infrastructuur van het internet.",
          "title": "Verdiep je kennis"
        },
        "share-knowledge": {
          "description": "Vertel anderen over de risico's van BGP-hijacking. Duw bijvoorbeeld Packet Panic onder hun neus.",
          "title": "Deel je kennis"
        },
        "title": "Wat kun je nu verder doen"
      }
    },
    "game-over-screen": {
      "full": "Volledig",
      "news-today": "Nieuws van vandaag",
      "read-article": "artikel lezen"
    },
    "global": {
      "back": "Terug",
      "continue": "Doorgaan",
      "level": "level",
      "share": "Delen",
      "skip": "Overslaan"
    },
    "intro-screen": {
      "about-packet-panic": "Over Packet Panic",
      "new-game": "Nieuw Spel",
      "paragraph": "Iedere seconde zijn miljarden pakketjes op weg naar hun eindbestemming op het internet. Deze stukjes data reizen van router naar router, vaak over de grenzen van meerdere autonome systemen. Ze vertrouwen blind op het Border Gateway Protocol (BGP) om de beste route te kiezen. Maar het BGP werkt op basis van informatie die het krijgt van andere netwerken, en die informatie is niet altijd correct…",
      "start": "Beginnen",
      "terms": {
        "autonome-systemen": {
          "explanation": "Een autonoom systeem is een verzameling netwerken onder het beheer van één organisatie, zoals een internetprovider of een groot bedrijf.",
          "term": "autonome systemen"
        },
        "bgp": {
          "explanation": "Het BGP is het protocol dat gebruikt wordt om de beste route te bepalen naar een bestemming die buiten het huidige autonome systeem ligt",
          "term": "Border Gateway Protocol"
        },
        "pakketjes": {
          "explanation": "Een pakketje is een stukje data, bijvoorbeeld: een e-mail, een videostream of een verzoek om een website te bezoeken.",
          "term": "pakketjes"
        },
        "router": {
          "explanation": "Een router stuurt pakketjes door naar de volgende halte op basis van instructies van protocollen zoals het BGP.",
          "term": "router naar router"
        }
      }
    },
    "left-corner-piece": {
      "view-how-the-net-works": "Bekijk Hoe het Net Werkt"
    },
    "level-picker": {
      "choose-level": "Level kiezen"
    },
    "levels": {
      "level-1": {
        "description": "Stuur de gekleurde pakketjes naar de juiste gebouwen!",
        "news-article": {
          "content": "Het BGP werkt vaak prima. Maar wat de bedenkers niet hebben voorzien, is dat het internet een plek zou worden waar niet iedereen altijd eerlijk is. Door het gebrek aan authenticatie, kun je niet checken of een via BGP aangekondigde route klopt.",
          "title": "BGP: de achilleshiel van het internet"
        },
        "score-screen": {
          "fail": {
            "description": "Dat is ook een manier om het te doen. Maar niet de goede. Blijkbaar was het toch niet zo simpel...",
            "title": "Level niet gehaald..."
          },
          "success": {
            "description": "Lekker gewerkt zeg! Maar zonder mijn hulp was het natuurlijk niet gelukt. Toch?",
            "title": "Level gehaald!"
          }
        },
        "storyline": {
          "step-1": {
            "button": "...",
            "text": "Welkom op je eerste werkdag als verkeersleider bij Packet Panic B.V."
          },
          "step-2": {
            "button": "...",
            "text": "Het meest prestigieuze autonome systeem van Nederland."
          },
          "step-3": {
            "button": "Ja, baas...",
            "text": "Mijn naam is D.I.R.K (Digitale Interne Routing Kracht). Maar jij mag me gewoon 'baas' noemen."
          },
          "step-4": {
            "button": "Oké!",
            "text": "Je hebt het simpelste baantje op aarde. Het BGP vertelt je de beste route voor ieder pakketje."
          },
          "step-5": {
            "button": "Ik snap het",
            "text": "Jij hoeft alleen maar te zorgen dat iedere wegwijzer de goede kant op wijst. Makkie toch?"
          },
          "step-6": {
            "button": "...",
            "text": "Tenzij het BGP je de verkeerde route doorgeeft. Dan wordt het ingewikkeld. "
          },
          "step-7": {
            "button": "Eh...",
            "text": "Maar dat gebeurt waarschijnlijk niet..."
          },
          "step-8": {
            "button": "Bedankt...",
            "text": "Oké. Dan kom je er wel uit hé. Succes!"
          }
        },
        "tutorial": {
          "step-1": "Stuur de pakketjes de goede kant op.",
          "step-2": "De pakketjes volgen richting van de wegwijzer.",
          "step-3": "De vlaggetjes geven aan wat de beste route is volgens het BGP.",
          "step-4": "Wat de beste route is kan tijdens het level veranderen. Nieuwe vlaggetjes geven de nieuwe route aan, de oude worden doorzichtig en verdwijnen vervolgens.",
          "step-5": "Beweeg de muis met de linkermuisknop ingedrukt om de camera te draaien.",
          "step-6": "Scroll met je muiswiel om in en uit te zoomen."
        }
      },
      "level-2": {
        "description": "Stuur de gekleurde pakketjes naar de juiste gebouwen!",
        "news-article": {
          "content": "In maart 2008 lag YouTube voor miljoenen gebruikers urenlang plat. De Pakistaanse overheid probeerde YouTube in hun land te blokkeren. Maar door een fout in de BGP-configuratie stuurden ze juist verkeer uit andere landen naar Pakistaanse netwerken.",
          "title": "BGP-foutje Pakistan legt Youtube plat"
        },
        "notifications": ["YouTube is niet bereikbaar.", "Krijg foutmelding bij YouTube.", "Kan YouTube niet laden.", "Website niet bereikbaar."],
        "score-screen": {
          "fail": {
            "description": "Helaas pindakaas... Maar we geven de moed niet op en proberen het gewoon nog een keer. Toch? Toch?",
            "title": "Level niet gehaald..."
          },
          "success": {
            "description": "Yes! Gelukt. Wat zijn we toch een fantastisch team! Vind je ook niet?",
            "title": "Level gehaald!"
          }
        },
        "storyline": {
          "step-1": {
            "button": "Nee",
            "text": "Dus je hebt gister helemaal geen problemen met het BGP ervaren?"
          },
          "step-2": {
            "button": "Ja?",
            "text": "Alles wat mis ging was je eigen fout?"
          },
          "step-3": {
            "button": "...",
            "text": "De wonderen zijn de wereld nog niet uit..."
          },
          "step-4": {
            "button": "Verder",
            "text": "Laten we hopen dat dat vandaag zo blijft!"
          }
        },
        "tutorial": {
          "step-1": "Pakketje gaan nu langs meerdere wegwijzers, zet ze allemaal goed als een route wijzigt."
        }
      },
      "level-3": {
        "description": "Stuur de gekleurde pakketjes naar de juiste gebouwen!",
        "news-article": {
          "content": "In september 2022 leidde een fout bij Amazon tot de diefstal van 235.000 dollar aan cryptocurrency. Verkeer werd omgeleid naar een nepwebsite die eruitzag als een legitieme cryptocurrency-dienst, waar hackers de bezoekers hun crypto afhandig maakten.",
          "title": "$235,000 aan cryptocurrency gestolen door BGP-hijack"
        },
        "notifications": ["Kan de website niet laden.", "Website niet bereikbaar."],
        "score-screen": {
          "fail": {
            "description": "Oh jee... Volgens mij heb je het internet kapotgemaakt. Wil je misschien even een momentje voor jezelf?",
            "title": "Level niet gehaald..."
          },
          "success": {
            "description": "Wauw, je bent hier goed in. Daar zou je iets mee moeten doen. Verkeersleider. Of pakketjesbezorger!",
            "title": "Level gehaald!"
          }
        },
        "serious-notifications": ["Mijn crypto is verdwenen door deze nepwebsite!", "Mijn digitale munten zijn weg! Dit was een scam!", "Ik ben opgelicht! Al mijn crypto is verdwenen!", "Mijn crypto is weg! Dit was een nepwebsite!"],
        "storyline": {
          "step-1": {
            "button": "...",
            "text": "Eén klein foutje..."
          },
          "step-2": {
            "button": "...",
            "text": "YouTube urenlang onbereikbaar."
          },
          "step-3": {
            "button": "YEAH!",
            "text": "Nouja, gelukkig was het niet onze schuld! Go team Packet Panic!"
          },
          "step-4": {
            "button": "...",
            "text": "Maar ontevreden klanten zijn wel een probleem."
          },
          "step-5": {
            "button": "...",
            "text": "Dus als je merkt dat BGP het bij het verkeerde eind heeft."
          },
          "step-6": {
            "button": "Oké!",
            "text": "Negeer de vlaggetjes en stuur het verkeer via een andere route."
          },
          "step-7": {
            "button": "RAAAWR!",
            "text": "Go get 'm tiger!"
          }
        },
        "tutorial": {
          "step-1": "Vermijd strafpunten! Leidt het verkeer om zodra je ziet dat verkeer niet aankomt bij een nieuwe route."
        },
        "warnings": ["Let op, deze site lijkt onveilig!", "Waarschuwing: Website niet helemaal oké.", "De website komt niet helemaal betrouwbaar over.", "Deze website lijkt verdacht."]
      },
      "level-4": {
        "description": "Stuur de gekleurde pakketjes naar de juiste gebouwen!",
        "news-article": {
          "content": "RPKI gebruikt digitale handtekeningen om BGP-routes te verifiëren. Routers controleren of de handtekeningen kloppen; zo niet dan wordt de route verworpen, wat aanvallen en vergissingen voorkomt.",
          "title": "RPKI: een veiliger BGP binnen handbereik"
        },
        "notifications": ["Kan de website niet laden.", "Website niet bereikbaar."],
        "score-screen": {
          "fail": {
            "description": "Dit is de voicemail van D.I.R.K. Ik ben helaas niet beschikbaar om je positieve of negatieve feedback te geven. Probeer het later nog eens.",
            "title": "Level niet gehaald..."
          },
          "success": {
            "description": "Dit is de voicemail van D.I.R.K. Ik ben helaas niet beschikbaar om je positieve of negatieve feedback te geven. Probeer het later nog eens.",
            "title": "Level gehaald!"
          }
        },
        "serious-notifications": ["Mijn crypto is verdwenen door deze nepwebsite!", "Mijn digitale munten zijn weg! Dit was een scam!", "Ik ben opgelicht! Al mijn crypto is verdwenen!", "Mijn crypto is weg! Dit was een nepwebsite!"],
        "storyline": {
          "step-1": {
            "button": "...",
            "text": "Ik heb een nieuwshamburger voor je: slecht nieuws, goed nieuws en slecht nieuws."
          },
          "step-10": {
            "button": "Ik ga je missen, baas!",
            "text": "Als ik geen paniek meer kan zaaien, zet ik mijn diensten liever ergens anders in."
          },
          "step-11": {
            "button": ":(",
            "text": "Zeg maar D.I.R.K., ik ben je baas niet meer..."
          },
          "step-12": {
            "button": "In a while, crocodile!",
            "text": "See you later, alligator!"
          },
          "step-2": {
            "button": "Goed nieuws",
            "text": "Welke wil je eerst?"
          },
          "step-3": {
            "button": "...",
            "text": "Ik begin toch met het slechte nieuws."
          },
          "step-4": {
            "button": "Oh, balen...",
            "text": "Het is zeer waarschijnlijk dat er veel minder crypto was gestolen als wij wat sneller hadden gereageerd."
          },
          "step-5": {
            "button": "En het laatste slechte nieuws?",
            "text": "Het goede nieuws is dat ik gelijk actie heb ondernomen: vanaf nu hebben we veel betere beveiliging in ons autonome systeem"
          },
          "step-6": {
            "button": "...",
            "text": "Oh ja, het belangrijkste nieuws..."
          },
          "step-7": {
            "button": "...",
            "text": "Je werk wordt een stuk minder interessant. Saai, zou ik wel durven zeggen."
          },
          "step-8": {
            "button": "...",
            "text": "Ze zitten er zelfs aan te denken het bedrijf een nieuwe naam te geven: CalmConnect"
          },
          "step-9": {
            "button": "Oh, nee!",
            "text": "Dus ik heb m'n ontslag ingediend."
          }
        },
        "tutorial": {
          "step-1": "Een uitroepteken geeft aan dat de route niet betrouwbaar is, vermijdt deze routes."
        },
        "warnings": ["Let op, deze site lijkt onveilig!", "Waarschuwing: Website niet helemaal oké.", "De website komt niet helemaal betrouwbaar over.", "Deze website lijkt verdacht."]
      }
    },
    "pause-screen": {
      "about-packet-panic": "Over Packet Panic",
      "back-to-home": "Terug naar home",
      "choose-level": "Level kiezen",
      "continue-playing": "Verder spelen",
      "paused": "Gepauzeerd"
    }
  }
}

export default Resources;
