// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "translation": {
    "about-packet-panic": {
      "paragraph1": "Packet Panic is een educatief spel dat is ontwikkeld door Studio Tast voor de SIDN-call 'Internet in beeld' om de onderliggende infrastructuur van het internet begrijpelijk uit te leggen.",
      "paragraph2": "Packet Panic focust op de gevaren van BGP-hijacking: het manipuleren en onderscheppen van internetverkeer door cybercriminelen. Het BGP is een essentieel, maar kwetsbaar onderdeel van het internet. Het internet is ontwikkeld door een groep onderzoekers die op basis van vertrouwen met elkaar samenwerkten. Het BGP gaat nog steeds uit van datzelfde onderlinge vertrouwen. Er zijn manieren om het BGP minder kwetsbaar te maken. Maar die zijn alleen effectief als die breed geimplementeerd worden. ",
      "paragraph3": "Het doel van Packet Panic is om meer mensen bewust te maken van de kwetsbaarheden van het Border Gateway Protocol (BGP). Via het spel krijgen spelers een inzicht in hoe BGP-hijacking werkt, wat de gevaren zijn en welke oplossingen er beschikbaar zijn.",
      "title": "Over Packet Panic"
    },
    "game-over-screen": {
      "full": "Volledig",
      "news-today": "Nieuws van vandaag",
      "read-article": "artikel lezen"
    },
    "global": {
      "back": "Terug",
      "continue": "Doorgaan",
      "level": "Level",
      "share": "Delen",
      "skip": "Overslaan"
    },
    "intro-screen": {
      "about-packet-panic": "Over Packet Panic",
      "new-game": "Nieuw Spel",
      "paragraph": "Iedere seconde zijn miljarden pakketjes op weg naar hun eindbestemming op het internet. Deze stukjes data reizen van router naar router, vaak over de grenzen van meerdere autonome systemen. Ze vertrouwen blind op het Border Gateway Protocol (BGP) om de beste route te kiezen. Maar het BGP werkt op basis van informatie die het krijgt van andere netwerken, en die informatie is niet altijd correct…",
      "start": "Beginnen",
      "terms": {
        "autonome-systemen": {
          "explanation": "Een autonoom systeem is een verzameling netwerken onder het beheer van één organisatie, zoals een internetprovider of een groot bedrijf.",
          "term": "autonome systemen"
        },
        "bgp": {
          "explanation": "Het BGP is het protocol dat gebruikt wordt om de beste route te bepalen naar een bestemming die buiten het huidige autonome systeem ligt",
          "term": "Border Gateway Protocol"
        },
        "pakketjes": {
          "explanation": "Een pakketje is een stukje data, bijvoorbeeld: een e-mail, een videostream of een verzoek om een website te bezoeken.",
          "term": "pakketjes"
        },
        "router": {
          "explanation": "Een router stuurt pakketjes door naar de volgende halte op basis van instructies van protocollen zoals het BGP.",
          "term": "router naar router"
        }
      }
    },
    "left-corner-piece": {
      "view-how-the-net-works": "Bekijk Hoe het Net Werkt"
    },
    "level-picker": {
      "choose-level": "Level kiezen"
    },
    "pause-screen": {
      "about-packet-panic": "Over Packet Panic",
      "back-to-home": "Terug naar home",
      "choose-level": "Level kiezen",
      "continue-playing": "Verder spelen",
      "paused": "Gepauzeerd"
    }
  }
}

export default Resources;
