// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "translation": {
    "about-packet-panic": {
      "paragraph1": "Packet Panic is een educatief spel dat is ontwikkeld door Studio Tast voor de SIDN-call 'Internet in beeld' om de onderliggende infrastructuur van het internet begrijpelijk uit te leggen.",
      "paragraph2": "Packet Panic focust op de gevaren van BGP-hijacking: het manipuleren en onderscheppen van internetverkeer door cybercriminelen. Het BGP is een essentieel, maar kwetsbaar onderdeel van het internet. Het internet is ontwikkeld door een groep onderzoekers die op basis van vertrouwen met elkaar samenwerkten. Het BGP gaat nog steeds uit van datzelfde onderlinge vertrouwen. Er zijn manieren om het BGP minder kwetsbaar te maken. Maar die zijn alleen effectief als die breed geimplementeerd worden. ",
      "paragraph3": "Het doel van Packet Panic is om meer mensen bewust te maken van de kwetsbaarheden van het Border Gateway Protocol (BGP). Via het spel krijgen spelers een inzicht in hoe BGP-hijacking werkt, wat de gevaren zijn en welke oplossingen er beschikbaar zijn.",
      "title": "Over Packet Panic"
    },
    "end-screen": {
      "go-to": "Ga naar",
      "news-review-title": "Terugblik krantenknipsels",
      "paragraph1": "Hopelijk heb je het gevoel gehad steeds achter de feiten aan te lopen. Wat als je meldingen krijgt dat een website niet beschikbaar is? Hoe weet je zeker dat een door het BGP aangekondigde route betrouwbaar is?",
      "paragraph2": "Packet Panic is bewust een frustrerend spel. Omdat BGP-hijacks een frustrerende realiteit zijn. RPKI is een goede oplossing, maar werkt pas echt goed bij 100% adoptie. Daar zijn we nog niet. De teller blijft vooralsnog steken op 50%",
      "paragraph3": "Nu weet jij dat ook. Dus help mee om RPKI adoptie naar 100% te krijgen.",
      "paragraph4": "Bedankt voor het spelen van Packet Panic.",
      "play-again": "Opnieuw spelen",
      "title": "Gefeliciteerd, je hebt Packet Panic voltooid!",
      "what-to-do": {
        "check-rpki": {
          "description": "en controleer hoe het zit met RPKI adoptie van je werkgever, je gemeente of je voetbalclub.",
          "title": "Check RPKI-adoptie"
        },
        "deepen-knowledge": {
          "description": "Bekijk de zusterprojecten van Packet Panic, die inzicht bieden in andere onderdelen van de infrastructuur van het internet.",
          "title": "Verdiep je kennis"
        },
        "share-knowledge": {
          "description": "Vertel anderen over de risico's van BGP-hijacking. Duw bijvoorbeeld Packet Panic onder hun neus.",
          "title": "Deel je kennis"
        },
        "title": "Wat kun je nu verder doen"
      }
    },
    "game-over-screen": {
      "full": "Volledig",
      "news-today": "Nieuws van vandaag",
      "read-article": "artikel lezen"
    },
    "global": {
      "back": "Terug",
      "continue": "Doorgaan",
      "level": "Level",
      "share": "Delen",
      "skip": "Overslaan"
    },
    "intro-screen": {
      "about-packet-panic": "Over Packet Panic",
      "new-game": "Nieuw Spel",
      "paragraph": "Iedere seconde zijn miljarden pakketjes op weg naar hun eindbestemming op het internet. Deze stukjes data reizen van router naar router, vaak over de grenzen van meerdere autonome systemen. Ze vertrouwen blind op het Border Gateway Protocol (BGP) om de beste route te kiezen. Maar het BGP werkt op basis van informatie die het krijgt van andere netwerken, en die informatie is niet altijd correct…",
      "start": "Beginnen",
      "terms": {
        "autonome-systemen": {
          "explanation": "Een autonoom systeem is een verzameling netwerken onder het beheer van één organisatie, zoals een internetprovider of een groot bedrijf.",
          "term": "autonome systemen"
        },
        "bgp": {
          "explanation": "Het BGP is het protocol dat gebruikt wordt om de beste route te bepalen naar een bestemming die buiten het huidige autonome systeem ligt",
          "term": "Border Gateway Protocol"
        },
        "pakketjes": {
          "explanation": "Een pakketje is een stukje data, bijvoorbeeld: een e-mail, een videostream of een verzoek om een website te bezoeken.",
          "term": "pakketjes"
        },
        "router": {
          "explanation": "Een router stuurt pakketjes door naar de volgende halte op basis van instructies van protocollen zoals het BGP.",
          "term": "router naar router"
        }
      }
    },
    "left-corner-piece": {
      "view-how-the-net-works": "Bekijk Hoe het Net Werkt"
    },
    "level-picker": {
      "choose-level": "Level kiezen"
    },
    "pause-screen": {
      "about-packet-panic": "Over Packet Panic",
      "back-to-home": "Terug naar home",
      "choose-level": "Level kiezen",
      "continue-playing": "Verder spelen",
      "paused": "Gepauzeerd"
    }
  }
}

export default Resources;
